shop/ishop/ZZShop/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from ZZShop import settings
from accounts import views
from accounts.views import home_view, signup_view,  activate, activation_sent_view

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),  # админкая страничка
    path('', home_view, name="index"),  # index
    path('signup/', signup_view, name="signup"),  # страничка регистрации
    path('sent/', activation_sent_view, name="activation_sent"),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),
    url(r'^account/', include('accounts.urls')),  # для аккаунтов
    path('shop/', include(('shop.urls', 'shop'), namespace="shop")),  # для магазинов
    path('wallet/', include('wallets.urls')),  # для кошельков
]
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # просмотр медиа файлов

shop/ishop/shop/urls.py
from django.template.context_processors import request
from django.views.generic import RedirectView, TemplateView
from django.urls import path

from .views import *


urlpatterns = [
    path('', HomeView.as_view(model=Product), name='home'),
    path('fence', HomeView.as_view(model=Fence), name='fence'),
    path('furniture', HomeView.as_view(model=Furniture), name='furniture'),
    path('paint', HomeView.as_view(model=Paint), name='paint'),
    path('interior', HomeView.as_view(model=Interior), name='interior'),
    path('exterior', HomeView.as_view(model=Exterior), name='exterior'),
    path('ground_coverage', HomeView.as_view(model=GroundCoverage), name='ground_coverage'),
    path('floor_coverage', HomeView.as_view(model=FloorCoverage), name='floor_coverage'),
    path('light', HomeView.as_view(model=Light), name='light'),
    path('plumbing', HomeView.as_view(model=Plumbing), name='plumbing'),
    path('cart/<slug>', add_to_cart, name='cart'),
    path('cart', BuyView.as_view(model=Cart, template_name="shop/cart.html"), name='cart_all'),
    path('remove/<slug>', remove_from_cart, name='remove-cart'),
    path('order', BuyView.as_view(model=Order, template_name="shop/order.html"), name='order'),
    path('None', RedirectView.as_view(pattern_name='shop:home'), name='buy'),
    path('shop', RedirectView.as_view(pattern_name='shop:home'), name='redirect'),
    path('add',  add_category, name='add'),
    path('add_product/<category>',  add_product, name='add_product'),
    path('delete/<slug>', delete_item, name='delete_item'),
    path('edit/<slug>/<category>', edit_product, name='edit_product'),
    path('deny', TemplateView.as_view(template_name='shop/deny.html'), name='deny'),
    path('approve', TemplateView.as_view(template_name='shop/approve.html'), name='approve'),
    path('export', create_report, name='export'),
    path('admin', create_admin_report, name='admin'),
    path('buy', buy, name='buy'),
    path('<slug>', ShowView.as_view(model=Product), name='show'),
    path('delete_order', delete_order, name='delete_order')
]

shop/ishop/signup/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url

from accounts import views
from accounts.views import home_view, signup_view, activation_sent_view, activate

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name="home"),
    path('signup/', signup_view, name="signup"),
    #path('sent/', activation_sent_view, name="activation_sent"),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),
]

shop/ishop/templates/activation_invalid.html
{% extends "home.html" %}
{% block content %}
    <div class="header-content">Wrong link. Try one more time. If problem is still, contact: admin@ikea20.tech </div>
{% endblock %}

shop/ishop/templates/activation_request.html
{% autoescape off %}
Hi {{ user.username }},

Please click the following link to confirm your registration:

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

shop/ishop/templates/activation_sent.html
{% extends "home.html" %}
{% block content %}
    <div class="header-content">Activation link sent! Please check your email. </div>
{% endblock %}

shop/ishop/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
{% extends "home.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
{% if request.user.is_authenticated %}
 <div class="col-lg-6">
	<div class="text-container">
	    <h1>Dashboard<br></h1>
	    <h2>Welcome to your dashboard</h2>
	    <p class="p-large">Your name, {{ request.user }}<br>
	    	E-mail: {{ request.user.email }}<br>
	    	Country: {{ request.user.profile.country }}<br>
	    	Admin: {{ request.user.is_staff }}<br>
	    </p>
	</div>
</div> <!-- end of col -->

{% endif %}
{% endblock %}
</html>

shop/ishop/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- SEO Meta Tags -->
    <meta name="description" content="Free mobile app HTML landing page template to help you build a great online presence for your app which will convert visitors into users">
    <meta name="author" content="Inovatik">

    <!-- OG Meta Tags to improve the way the post looks when you share the page on LinkedIn, Facebook, Google+ -->
	<meta property="og:site_name" content="" /> <!-- website name -->
	<meta property="og:site" content="" /> <!-- website link -->
	<meta property="og:title" content=""/> <!-- title shown in the actual shared post -->
	<meta property="og:description" content="" /> <!-- description shown in the actual shared post -->
	<meta property="og:image" content="" /> <!-- image link, make sure it's jpg -->
	<meta property="og:url" content="" /> <!-- where do you want your post to link to -->
	<meta property="og:type" content="article" />

    <!-- Website Title -->
    <title>Shop</title>
    
    <!-- Styles -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700,700i" rel="stylesheet">
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <link href="/static/css/fontawesome-all.css" rel="stylesheet">
    <link href="/static/css/swiper.css" rel="stylesheet">
	<link href="/static/css/magnific-popup.css" rel="stylesheet">
	<link href="/static/css/styles.css" rel="stylesheet">
    <link href="/static/css/navbar.css" rel="stylesheet">
    <link href="/static/css/great_btn.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">

	<!-- Favicon  -->
    <link rel="icon" href="/static/images/favicon.jpg">


    <!-- Scroll -->

</head>
<body data-spy="scroll" data-target=".fixed-top">
    
    <!-- Preloader -->
	<div class="spinner-wrapper">
        <div class="spinner">
            <div class="bounce1"></div>
            <div class="bounce2"></div>
            <div class="bounce3"></div>
        </div>
    </div>
    <!-- end of preloader -->
    

    <!-- Navbar -->
    <nav class="navbar navbar-expand-md navbar-dark navbar-custom fixed-top">
        <!-- Text Logo - Use this if you don't have a graphic logo -->
        <!-- <a class="navbar-brand logo-text page-scroll" href="index.html">Leno</a> -->

        <!-- Mobile Menu Toggle Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-awesome fas fa-bars"></span>
            <span class="navbar-toggler-awesome fas fa-times"></span>
        </button>
        <!-- end of mobile menu toggle button -->

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav ml-auto nav navbar-menu">
                <li class="nav-item">
                    <a class="nav-link page-scroll a-menu" href="#header">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link page-scroll a-menu" href="{% url "shop:cart_all" %}">Carts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link page-scroll a-menu" href="{% url "shop:order" %}">Orders</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link page-scroll a-menu" href="{% url "shop:home" %}">Shop</a>
                </li>

                <!-- Dropdown Menu -->          
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle page-scroll a-menu" href="#details" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">Account</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url "profile" %}#features"><span class="item-text">DashBoard</span></a>
                        {% if request.user.is_authenticated %}
                    	<a class="dropdown-item" href="{% url "logout" %}"><span class="item-text">
				            <div class="dropdown-items-divide-hr"></div>
                        	LogOut</span></a>
				        {% else %}
				        <a class="dropdown-item" href="{% url "login" %}"><span class="item-text">
				            <div class="dropdown-items-divide-hr"></div>
                        	LogIn</span></a>
                        <a class="dropdown-item" href="{% url "signup" %}"><span class="item-text">
				            <div class="dropdown-items-divide-hr"></div>
                        	SignUp</span></a>
				        {% endif %}
                    </div>
                </li>
                <!-- end of dropdown menu -->
            </ul>
        </div>
    </nav> <!-- end of navbar -->
    <!-- end of navbar -->


    <!-- Header -->
    <header id="header" class="header">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="text-container">
                            <h1>BEST SHOP WITH <br>FENCES, FURNITURE, PAINTINGS, COVERAGE</h1>
                            <p class="p-large">Welcome in IKEA2.0 !</p>
                            {% if request.user.is_authenticated %}
                            <a class="btn-solid-lg page-scroll" href="{% url "logout" %}">LOGOUT</a>
                            {% else %}
                            <a class="btn-solid-lg page-scroll" href="{% url "signup" %}">REGISTER</a>
                            <a class="btn-solid-lg page-scroll" href="{% url "login" %}">LOGIN</a>
                            {% endif %}
                        </div>
                    </div> <!-- end of col -->
                    <div class="col-lg-6">
                        <div class="image-container">
                            <img class="img-fluid" src="" alt="">
                        </div> <!-- end of image-container -->
                    </div> <!-- end of col -->
                </div> <!-- end of row -->
    </header> <!-- end of header -->
    <!-- end of header -->
    

    <!-- Features -->
    <div id="features" class="tabs">
        <div class="container">
            <div class="row border-right-0">
               {% block content %}
               Hi there, home page
               {% endblock %}
            </div>
        </div>
    </div>
                
    <!-- Footer -->
    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="footer-col">
                        <h4>About IKEA2.0</h4>
                        <p>This is great shop of interior and exterior things for your house</p>
                    </div>
                </div> <!-- end of col -->
                 <div class="col-lg-6">
                    <div class="footer-col middle">
                        <h4>Important Links</h4>
                        <ul class="list-unstyled li-space-lg">
                            <li class="media">
                                <i class="fas fa-square"></i>
                                <div class="media-body">There are no Terms & ConditionsRead or Privacy Policy yet, lol</div>
                            </li>
                        </ul>
                    </div>
                </div> <!-- end of col -->
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </div> <!-- end of footer -->  
    <!-- end of footer -->


    <!-- Copyright -->
    <div class="copyright">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p class="p-small">Template was taken fom <a href="http://www.inovatik.com">Inovatik</a></p>
                </div> <!-- end of col -->
            </div> <!-- enf of row -->
        </div> <!-- end of container -->
    </div> <!-- end of copyright --> 
    <!-- end of copyright -->
    
    	
    <!-- Scripts -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/egg.js/1.0/egg.min.js"></script>
    <script src="/static/js/navbar_flow.js"></script>
    <script src="/static/js/eggs.js"></script>
    <script src="/static/js/jquery.min.js"></script> <!-- jQuery for Bootstrap's JavaScript plugins -->
    <script src="/static/js/popper.min.js"></script> <!-- Popper tooltip library for Bootstrap -->
    <script src="/static/js/bootstrap.min.js"></script> <!-- Bootstrap framework -->
    <script src="/static/js/jquery.easing.min.js"></script> <!-- jQuery Easing for smooth scrolling between anchors -->
    <script src="/static/js/swiper.min.js"></script> <!-- Swiper for image and text sliders -->
    <script src="/static/js/jquery.magnific-popup.js"></script> <!-- Magnific Popup for lightboxes -->
    <script src="/static/js/morphext.min.js"></script> <!-- Morphtext rotating text in the header -->
    <script src="/static/js/validator.min.js"></script> <!-- Validator.js - Bootstrap plugin that validates forms -->
    <script src="/static/js/scripts.js"></script> <!-- Custom scripts -->
</body>
</html>

shop/ishop/templates/home3.html
{% load static %}
{% include 'material/includes/material_css.html' %}
{% include 'material/includes/material_js.html' %}
{% load material_form %}
<!DOCTYPE html>
<html lang="Ru">
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "material/css/materialize.css" %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700,700i" rel="stylesheet">
</head>
<body>
<div id="header">
    <span class="logo">Shop</span>
    {% if request.user.is_authenticated %}
        <ul class="menu">
            <li {% if section == "profile" %}class="selected"{% endif %}>
            <a href="{% url "index" %}">Home</a>
            </li>
            <li {% if section == "register" %}class="selected"{% endif %}>
            <a href="{% url "signup" %}">Sign Up</a>
            </li>
            <li {% if section == "dashboard" %}class="selected"{% endif %}>
            <a href="{% url "profile" %}">My dashboard</a>
            </li>
            <li {% if section == "orders" %}class="selected"{% endif %}>
            <a href="{% url "order" %}">Orders</a>
            </li>
            <li {% if section == "carts" %}class="selected"{% endif %}>
                <a href="{% url "cart_all" %}">Carts</a>
            </li>
            <li {% if section == "shop" %}class="selected"{% endif %}>
                <a href="{% url "home" %}">Shop</a>
            </li>
        </ul>
    {% endif %}
    <span class="user">
        {% if request.user.is_authenticated %}
            Hello {{ request.user.first_name }},
            <a href="{% url "logout" %}">Logout</a>
        {% else %}
            <a href="{% url "login" %}">Log-in</a>
        {% endif %}
    </span>
</div>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

shop/ishop/templates/login.html
{% extends "home.html" %}
{% block title %}Log-in{% endblock %}
{% block content %}
    <div class="counter-value">
    <h1>Log-in</h1><br/>
    <h1></h1>
    {% if form.errors %}
        <h2>
            Your username and password didn't match.
            Please try again.
        </h2>
    {% else %}
        <h2>Please, use the following form to log-in:</h2>
    {% endif %}
    <h1></h1>
    <div class="login-form">
        <form action="{% url 'login' %}" method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}"/>
            <p><input type="submit" value="Log-in" class="btn-outline-reg"></p>
        </form>
    </div>
    </div>
{% endblock %}

shop/ishop/templates/logout.html
{% extends "home.html" %}
{% block title %}Logged out{% endblock %}
{% block content %}
    <div style="text-align: center;"><h1>Logged out</h1><br></div>

    <h5>You have been successfully logged out. You can <a href="{% url "login" %}">log-in again</a>.</h5>
{% endblock %}

shop/ishop/templates/signup.html
{% extends "home.html" %}
{% block content %}
<div class="counter-value mx-4">
<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
    <table class="table table-borderless center text-white">
  {% for field in form %}
    <p>
    <tr>
    <td>
      {{ field.label_tag }}
    </td>
    <td>
      {{ field }}
    </td>
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
     </tr>
    </p>
  {% endfor %}
    </table>
  <button type="submit" class="btn-outline-reg">Sign up</button>
</form>
</div>
{% endblock %}