shop/ishop/ZZShop/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from ZZShop import settings
from accounts import views
from accounts.views import home_view, signup_view,  activate, activation_sent_view

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),  # админкая страничка
    path('', home_view, name="index"),  # index
    path('signup/', signup_view, name="signup"),  # страничка регистрации
    path('sent/', activation_sent_view, name="activation_sent"),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),
    url(r'^account/', include('accounts.urls')),  # для аккаунтов
    path('shop/', include(('shop.urls', 'shop'), namespace="shop")),  # для магазинов
    path('wallet/', include('wallets.urls')),  # для кошельков
]
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # просмотр медиа файлов

shop/ishop/shop/urls.py
from django.template.context_processors import request
from django.views.generic import RedirectView, TemplateView
from django.urls import path

from .views import *


urlpatterns = [
    path('', HomeView.as_view(model=Product), name='home'),
    path('fence', HomeView.as_view(model=Fence), name='fence'),
    path('furniture', HomeView.as_view(model=Furniture), name='furniture'),
    path('paint', HomeView.as_view(model=Paint), name='paint'),
    path('interior', HomeView.as_view(model=Interior), name='interior'),
    path('exterior', HomeView.as_view(model=Exterior), name='exterior'),
    path('ground_coverage', HomeView.as_view(model=GroundCoverage), name='ground_coverage'),
    path('floor_coverage', HomeView.as_view(model=FloorCoverage), name='floor_coverage'),
    path('light', HomeView.as_view(model=Light), name='light'),
    path('plumbing', HomeView.as_view(model=Plumbing), name='plumbing'),
    path('cart/<slug>', add_to_cart, name='cart'),
    path('cart', BuyView.as_view(model=Cart, template_name="shop/cart.html"), name='cart_all'),
    path('remove/<slug>', remove_from_cart, name='remove-cart'),
    path('order', BuyView.as_view(model=Order, template_name="shop/order.html"), name='order'),
    path('None', RedirectView.as_view(pattern_name='shop:home'), name='buy'),
    path('shop', RedirectView.as_view(pattern_name='shop:home'), name='redirect'),
    path('add',  add_category, name='add'),
    path('add_product/<category>',  add_product, name='add_product'),
    path('delete/<slug>', delete_item, name='delete_item'),
    path('edit/<slug>/<category>', edit_product, name='edit_product'),
    path('deny', TemplateView.as_view(template_name='shop/deny.html'), name='deny'),
    path('approve', TemplateView.as_view(template_name='shop/approve.html'), name='approve'),
    path('export', create_report, name='export'),
    path('admin', create_admin_report, name='admin'),
    path('buy', buy, name='buy'),
    path('<slug>', ShowView.as_view(model=Product), name='show'),
    path('delete_order', delete_order, name='delete_order')
]

shop/ishop/signup/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url

from accounts import views
from accounts.views import home_view, signup_view, activation_sent_view, activate

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name="home"),
    path('signup/', signup_view, name="signup"),
    #path('sent/', activation_sent_view, name="activation_sent"),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),
]

shop/ishop/shop/models/goods.py
from django.db import models
from djmoney.models.fields import MoneyField
from shop import settings

CATEGORY_CHOICES = (
    ('Product', 'Product'),
    ('Interior', 'Interior'),
    ('Exterior', 'Exterior'),
    ('GroundCoverage', 'GroundCoverage'),
    ('Fence', 'Fence'),
    ('Paint', 'Paint'),
    ('Light', 'Light'),
    ('FloorCoverage', 'FloorCoverage'),
    ('Plumbing', 'Plumbing'),
    ('Furniture', 'Furniture'),
)


class Product(models.Model):
    slug = models.AutoField(primary_key=True)
    category = models.CharField(max_length=15, verbose_name='Category', choices=CATEGORY_CHOICES, default="Product")
    img = models.ImageField(upload_to='shop', blank=True)
    name = models.CharField(max_length=300)
    preview_text = models.TextField(max_length=200, verbose_name='Preview Text')
    detail_text = models.TextField(max_length=1000, verbose_name='Detail Text')
    price = MoneyField(max_digits=14, decimal_places=2, default_currency='USD')
    discount_price = MoneyField(max_digits=14, decimal_places=2, default_currency='USD')
    seller = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default='1')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.category = self.class_name()

    def class_name(self):
        return self.__class__.__name__

    def __str__(self):
        return self.name

    def get_template_img(self):
        print(self.img.path.replace('shop/', ''))

    def get_value(self):
        return [self.slug, self.category, self.name, self.preview_text, self.detail_text, self.price,
                self.discount_price, self.seller]

    @staticmethod
    def count_value():
        return 8


class Exterior(Product):
    is_water_prooved = models.BooleanField(default=False)
    brand = models.TextField(max_length=200, verbose_name='Brand name')


class GroundCoverage(Exterior):
    sport_compatibility = models.BooleanField(default=False)
    warranty = models.IntegerField(default=0)


class Fence(Exterior):
    is_three_dim = models.BooleanField(default=False)
    type = models.TextField(max_length=200, verbose_name='Type')


class Interior(Product):
    warranty = models.IntegerField(default=0)
    child_compatibility = models.BooleanField(default=False)


class Plumbing(Interior):
    capacity = models.IntegerField(default=0)
    # better to enum !
    type = models.TextField(max_length=200, verbose_name='Type')


class Light(Interior):
    power = models.IntegerField(default=0)
    # better to enum !
    style = models.TextField(max_length=200, verbose_name='Type')
    lux = models.IntegerField(default=0)
    temperature = models.IntegerField(default=0)


class FloorCoverage(Interior):
    vacuum_compatibility = models.BooleanField(default=False)
    # better to enum !
    type = models.TextField(max_length=200, verbose_name='Type')
    brand = models.TextField(max_length=200, verbose_name='Brand')
    fits_for = models.TextField(max_length=200, verbose_name='Main coverage material')


class Paint(Interior):
    painter = models.TextField(max_length=200, verbose_name='Name of painter')
    style = models.TextField(max_length=200, verbose_name='Style')
    year = models.IntegerField(default=0)


class Furniture(Interior):
    pet_compatibility = models.BooleanField(default=False)
    # better to enum !
    type = models.TextField(max_length=200, verbose_name='Type')
    brand = models.TextField(max_length=200, verbose_name='Brand')
    style = models.TextField(max_length=200, verbose_name='Style')

shop/ishop/shop/forms.py
from django import forms
from django.forms import BaseModelForm
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget
from djmoney.models.fields import MoneyField
from djmoney.money import Money

from shop.models import *


class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('img', 'name', 'preview_text', 'detail_text', 'price', 'discount_price',)


class AddExteriorForm(forms.ModelForm):
    class Meta:
        model = Exterior
        fields = ('img', 'name', 'preview_text', 'detail_text', 'price', 'discount_price',
                  'is_water_prooved', 'brand',)


class AddGroundCoverageForm(forms.ModelForm):
    class Meta:
        model = GroundCoverage
        fields = ('img', 'name', 'preview_text', 'detail_text', 'price',
                  'discount_price', 'is_water_prooved', 'brand',
                  'sport_compatibility', 'warranty',)


class AddFenceForm(forms.ModelForm):
    class Meta:
        model = Fence
        fields = ('img', 'name', 'preview_text', 'detail_text', 'price',
                  'discount_price', 'is_water_prooved', 'brand',
                  'is_three_dim', 'type',)


class AddInteriorForm(forms.ModelForm):
    class Meta:
        model = Interior
        fields = ('img', 'name', 'preview_text', 'detail_text', 'price',
                  'discount_price', 'warranty', 'child_compatibility',)


class AddPlumbingForm(forms.ModelForm):
    class Meta:
        model = Plumbing
        fields = ('img', 'name', 'preview_text', 'detail_text', 'price',
                  'discount_price', 'warranty', 'child_compatibility',
                  'capacity', 'type',)


class AddLightForm(forms.ModelForm):
    class Meta:
        model = Light
        fields = ('img', 'name', 'preview_text', 'detail_text', 'price',
                  'discount_price', 'warranty', 'child_compatibility',
                  'power', 'style', 'temperature', 'lux',)


class AddFloorCoverageForm(forms.ModelForm):
    class Meta:
        model = FloorCoverage
        fields = ('img', 'name', 'preview_text', 'detail_text', 'price',
                  'discount_price', 'warranty', 'child_compatibility',
                  'vacuum_compatibility', 'type', 'brand', 'fits_for',)


class AddPaintForm(forms.ModelForm):
    class Meta:
        model = Paint
        fields = ('img', 'name', 'preview_text', 'detail_text', 'price',
                  'discount_price', 'warranty', 'child_compatibility',
                  'painter', 'style', 'year',)


class AddFurnitureForm(forms.ModelForm):
    class Meta:
        model = Furniture
        fields = ('img', 'name', 'preview_text', 'detail_text', 'price',
                  'discount_price', 'warranty', 'child_compatibility',
                  'pet_compatibility', 'type', 'brand', 'style',)


class AddCategoryForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('category',)

shop/ishop/shop/views/cart_order.py
import stripe
import logging
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from shop.models import *

stripe.api_key = settings.STRIPE_SECRET_KEY
logger = logging.getLogger(__name__)


@login_required()
def buy(request):
    current_order = Order.objects.filter(user=request.user.profile)[0]
    if current_order.buy() == 'deny':
        logger.warning("Fail buy for {}".format(request.user.profile.get_profile()))
        return HttpResponseRedirect('../shop/deny')
    logger.info("Successful buy for {}".format(request.user.profile.get_profile()))
    return HttpResponseRedirect('../shop/approve')


@login_required()
def delete_order(request):
    current_order = Order.objects.filter(user=request.user.profile)
    current_order.delete()
    logger.info("Order deleted: {}".format(current_order))
    return redirect("..")


@login_required()
def add_to_cart(request, slug):
    item = get_object_or_404(Product, slug=slug)
    user = request.user.profile.get_profile()
    order_item, created = Cart.objects.get_or_create(
        item=item,
        user=request.user.profile.get_profile()
    )
    order_item.add_to_cart(item, user)
    logger.info("Order of {} successful added for: {}".format(item, user))
    return redirect("..")


def remove_from_cart(request, slug):
    item = get_object_or_404(Product, slug=slug)
    cart_qs = Cart.objects.filter(user=request.user.profile, item=item)
    if cart_qs.exists():
        current_cart = cart_qs[0]
        current_cart.remove_from_avail_cart(cart_qs)
    order_qs = Order.objects.filter(
        user=request.user.profile,
        ordered=False
    )
    if order_qs.exists():
        current_order = order_qs[0]
        current_order.remove_current_order(item, request.user.profile)
        logger.info("Order of {} successful deleted for: {}".format(item, request.user.profile))
        return redirect("..")
    else:
        logger.info("Order of {} successful deleted for: {}".format(item, request.user.profile))
        return redirect("..")

shop/ishop/shop/views/goods.py
import logging

import stripe
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView

from shop.forms import *
from shop.models import *
from shop.transform import category_to_form_and_method, category_to_model
from shop.add_fields_to_category import *

stripe.api_key = settings.STRIPE_SECRET_KEY
logger = logging.getLogger(__name__)


class HomeView(ListView):
    model = Product
    paginate_by = 10
    ordering = 'slug'
    template_name = "shop/index.html"

class ShowView(DetailView):
    model = Product

class BuyView(ListView):
    model = Product
    template_name = "shop/index.html"


@login_required()
def add_category(request):
    if not request.user.profile.get_profile().is_seller:
        return HttpResponseRedirect('../shop')
    if request.method == 'POST':
        form = AddCategoryForm(request.POST)
        if form.is_valid():
            return HttpResponseRedirect('../shop/add_product/{}'.format(form.data.get('category')))
    else:
        form = AddCategoryForm()
    return render(request, 'shop/add_category.html', {'form': form})


@login_required()
def add_product(request, category):
    if not request.user.profile.get_profile().is_seller:
        logger.warning("{} tried to get access to add product".format(request.user.profile.get_profile()))
        return HttpResponseRedirect('../shop')
    add_specified_fields, form_of_category = category_to_form_and_method(category)
    if request.method == 'POST':
        form = form_of_category(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            add_specified_fields(product, form, request.user.profile, category)
            logger.info("Successful added product {} by {}".format(product, request.user.profile.get_profile()))
            return HttpResponseRedirect('../../shop')
    else:
        form = form_of_category()
    return render(request, 'shop/add_product.html', {'form': form})


@login_required()
def delete_item(request, slug):
    item = get_object_or_404(Product, slug=slug)
    if not item.seller == request.user.profile.get_profile():
        logger.info("Failed delete product {} by {}".format(item, request.user.profile.get_profile()))
        return HttpResponseRedirect('..')
    item.delete()
    logger.info("Successful deleted product {} by {}".format(item, request.user.profile.get_profile()))
    return HttpResponseRedirect('..')


@login_required()
def edit_product(request, slug, category):
    item = get_object_or_404(category_to_model(category), slug=slug)
    if not item.seller == request.user.profile.get_profile():
        return HttpResponseRedirect('..')
    add_specified_fields, form_of_category = category_to_form_and_method(category)
    if request.method == 'POST':
        form = form_of_category(request.POST, request.FILES, instance=item)
        if form.is_valid():
            product = item
            add_specified_fields(product, form, request.user.profile, category)
            product.save()
            logger.info("Successful edited product {} with id {} by {}".format(product, product.slug,
                                                                               request.user.profile.get_profile()))
            return HttpResponseRedirect('../../shop')
    else:
        form = form_of_category(instance=item)
    return render(request, 'shop/add_product.html', {'form': form})

shop/ishop/shop/views/reports.py
import stripe
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
import shop.models as md
import shop.models.report as report


@login_required()
def create_report(request):
    response = HttpResponse(content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename=Report.xlsx'
    xlsx_data = report.write_excel(md.Product.objects.all(), request.user.profile.get_profile())
    response.write(xlsx_data)
    return response


@login_required()
def create_admin_report(request):
    if not request.user.profile.user.is_superuser:
        return HttpResponseRedirect('http://google.com')
    response = HttpResponse(content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename=Report.xlsx'
    xlsx_data = report.admin_report()
    response.write(xlsx_data)
    return response

shop/ishop/templates/shop/home.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <div class="row wow fadeIn">

          {% for item in object_list %}
          <div class="col-lg-3 col-md-6 mb-4">

            <div class="card">

              <div class="view overlay">
                {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" {% endcomment %}
                <img src="{{ item.image.url }}" class="card-img-top">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <div class="card-body text-center">
                <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>$
                  {% if item.discount_price %}
                  {{ item.discount_price }}
                  {% else %}
                  {{ item.price }}
                  {% endif %}
                  </strong>
                </h4>

              </div>

            </div>

          </div>
          {% endfor %}
        </div>

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->

      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}

    </div>
  </main>

{% endblock content %}

shop/ishop/templates/shop/index.html
{% extends "../home.html" %}
{% block content %}
      {% for product in object_list %}
      <div class="col-md-4 col-sm-12 col-lg-3 m-1">
              <div class="card" style='width:100%; height:500px;'>
                <a href="/shop/{{ product.slug }}">
                <img src="{{ product.img.url }}" style="width:100%; height: 255px; border-radius: 10%;" class="card-img-top" alt="{{ product.name }}">
                </a>
                      <div class="card-body">
                        <h5 class="card-title"> {{ product.name }}</h5>
                        <p class="card-text">{{ product.preview_text }}</p>
                        <p class="card-text">{{ product.price }}</p>
                      </div>
                  <div class='card-footer text-center' style="height: 130px;">
                      <a href="cart/{{ product.slug }}" class="btn btn-success btn-jittery">Add to Cart</a>
                      <a href="remove/{{ product.slug }}" class="btn btn-danger btn-close">Remove from Cart</a>
                      {% if product.seller == request.user.profile.get_profile %}
                        <a href="edit/{{ product.slug }}/{{ product.category }}" class="btn btn-warning btn-jelly">Edit</a>
                          <a href="delete/{{ product.slug }}" class="btn btn-dark btn-open">Remove</a>
                      {% endif %}
                  </div>
               </div>
        </div>
    {% endfor %}
<div id="panel" class="d-none d-lg-block hide-on-portrait"> Parameters
    <div class="d-none d-lg-block" id="hidden_panel">
        <select class="form-control-select" name="category" onchange="(window.location = this.options[this.selectedIndex].value);">
            <option value ='{% url "shop:home" %}'>Select category</option>
            <option value ='{% url "shop:home" %}'>All</option>
            <option value ='{% url "shop:exterior" %}'>Exterior</option>
            <option value ='{% url "shop:ground_coverage" %}'>Ground Coverage</option>
            <option value ='{% url "shop:fence" %}'>Fences</option>
            <option value ='{% url "shop:interior" %}'>Interior</option>
            <option value ='{% url "shop:plumbing" %}'>Plumbing</option>
            <option value ='{% url "shop:furniture" %}'>Furniture</option>
            <option value ='{% url "shop:light" %}'>Light</option>
            <option value ='{% url "shop:floor_coverage" %}'>Floor Coverage</option>
            <option value ='{% url "shop:paint" %}'>Paint</option>
        </select>
        {% if request.user.profile.get_profile.is_seller %}
            <a href='{% url "shop:add" %}' class="btn btn-success btn-small active" role="button" aria-pressed="true">Add product</a>
        {% endif %}
        <a href='{% url "shop:export" %}' class="btn btn-primary btn-small active" role="button" aria-pressed="true">Export to Excel</a>
    </div>
  </div>
{% endblock %}

shop/ishop/templates/shop/product.html
{% extends "base.html" %}

{% block content %}

  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                <del>${{ object.price }}</del>
              </span>
              <span>${{ object.discount_price }}</span>
              {% else %}
              <span>${{ object.price }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.description }}</p>

            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary" type="submit">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}
            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
              Remove from cart
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>

{% endblock content %}

shop/ishop/templates/shop/product_detail.html
{% extends "../home.html" %}

{% block content %}

  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{ product.img.url }}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
                <h1>{{ object.name }}</h1>
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                <del>{{ object.price }}</del>
              </span>
              <span>{{ object.discount_price }}</span>
              {% else %}
              <span>{{ object.price }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.preview_text }}</p>

            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}
            <a href="cart/{{ product.slug }}" class="btn btn-success btn-jittery">Add to Cart</a>
            <a href="remove/{{ product.slug }}" class="btn btn-danger btn-close">Remove from Cart</a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

      </div>
      <!--Grid row-->
  </main>

{% endblock content %}